package com.chuangdata.userprofile.counter;

public enum UserProfileCounter {
    MAP_INVALID_INPUT_ERROR,
    MAP_ERROR,
    MAP_INVALID_INPUT_FIELDS_ERROR,
    MAP_FILTER_OUT,
    MAP_FILTER_OUT_BY_EMPTY_HOST,
    MAP_FILTER_OUT_BY_HOST,
    MAP_FILTER_OUT_BY_URI,
    MAP_FILTER_OUT_BY_TIME,
    MAP_FILTER_OUT_BY_DOMAIN,

    MAP_FILTER_OUT_BY_UNKNOW_DOMAIN,
    MAP_FILTER_OUT_BY_UNKNOW_APP,
    MAP_FILTER_OUT_BY_UNKNOW_ACTION,
    MAP_FILTER_OUT_BY_EMPTY_MEID,
    MAP_FILTER_OUT_BY_EMPTY_MEID15,
    MAP_FILTER_OUT_BY_EMPTY_MEID_MSISDN,

    REDUCE_OUTPUT_USERAGENT,
    REDUCE_OUTPUT_APP,
    REDUCE_OUTPUT_ACTION,
    REDUCE_OUTPUT_PARAM,
    REDUCE_OUTPUT_DOMAIN;
}
